# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cham's Blog
brief-intro: Algorithm, skill and thinking
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chamwen.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
github_username: chamwen
email: wenzn9@gmail.com
twitter_username: 
facebook_username: 
zhihu_username: 
linkedIn_username: 

description_footer: Chasing the unknown

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
baidu_tongji_id: 6c42715c371f7f46f5b2b6f9b17370ab
google_analytics_id: UA-148378835-1 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
port: 5555

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "<!--more-->"

# paginate
plugins:
  - jekyll-sitemap
  - jekyll-paginate
gems: [jekyll-paginate]
paginate: 6